version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: pipeline-db
    restart: always
    environment:
      POSTGRES_DB: pipeline_optimizer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5438:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: